### ISSUE TITLE
how do you run this?

### ISSUE THREAD

**Issue by Kreijstal** [catSIXe/tgfusefs#1]

**Comment by catSIXe** [comment]
currently its just a test
you need to crate a mountpoint [/home/user/telegram with mkdir](https://github.com/catSIXe/tgfusefs/blob/c07f42be664e784782cf88fe75d458f31dbd10c0/index.js#L31)

and a temporary mountpath [home/user/temp](https://github.com/catSIXe/tgfusefs/blob/c07f42be664e784782cf88fe75d458f31dbd10c0/index.js#L36)

start the index.js and follow the instructions "Enter phone number" /code/pw

**Comment by Kreijstal** [comment]
Maybe you should try creating a npm package to manage dependencies and what not automatically

**Comment by catSIXe** [comment]
just use "npm i"

Am 22.06.2020 um 07:16 schrieb Kreijstal:
